<a href="https://colab.research.google.com/github/jaydeep-aspire/practice/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print()

In [ ]:
import tensorflow_decision_forests as tfdf
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import math

In [ ]:
pd_dataset = pd.DataFrame({
    "feature_1": [1,2,3],
    "feature_2": ["a", "b", "c"],
    "label": [0, 1, 0],
})
pd_dataset

feature_1 feature_2  label
0          1         a      0
1          2         b      1
2          3         c      0

In [ ]:
tf_dataset = tfdf.keras.pd_dataframe_to_tf_dataset(pd_dataset,label="label")
for features,label in tf_dataset:
  print(features)
  print(label)

{'feature_1': <tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>, 'feature_2': <tf.Tensor: shape=(3,), dtype=string, numpy=array([b'a', b'b', b'c'], dtype=object)>}
tf.Tensor([0 1 0], shape=(3,), dtype=int64)


In [ ]:
pd_train_dataset = pd.DataFrame({
    "feature_1": np.random.rand(1000),
    "feature_2": np.random.rand(1000),
})
pd_train_dataset["label"] = pd_train_dataset["feature_1"] > pd_train_dataset["feature_2"]

pd_train_dataset

feature_1  feature_2  label
0     0.076360   0.076489  False
1     0.496966   0.580526  False
2     0.391952   0.835377  False
3     0.680075   0.348306   True
4     0.288121   0.579891  False
..         ...        ...    ...
995   0.714820   0.990924  False
996   0.591828   0.599496  False
997   0.151531   0.606155  False
998   0.097182   0.867915  False
999   0.595762   0.548140   True

[1000 rows x 3 columns]

In [ ]:
pd_serving_dataset = pd.DataFrame({
    "feature_1": np.random.rand(500),
    "feature_2": np.random.rand(500),
})

pd_serving_dataset

feature_1  feature_2
0     0.518046   0.340075
1     0.137975   0.468674
2     0.969765   0.496079
3     0.545643   0.602807
4     0.699625   0.398909
..         ...        ...
495   0.639369   0.629604
496   0.978312   0.432256
497   0.333568   0.939335
498   0.474098   0.600906
499   0.191318   0.358531

[500 rows x 2 columns]

from matplotlib import pyplot as plt
pd_serving_dataset['feature_1'].plot(kind='hist', bins=20, title='feature_1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
pd_serving_dataset['feature_2'].plot(kind='hist', bins=20, title='feature_2')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
pd_serving_dataset.plot(kind='scatter', x='feature_1', y='feature_2', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
pd_serving_dataset['feature_1'].plot(kind='line', figsize=(8, 4), title='feature_1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
pd_serving_dataset['feature_2'].plot(kind='line', figsize=(8, 4), title='feature_2')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
tf_train_dataset = tfdf.keras.pd_dataframe_to_tf_dataset(pd_train_dataset, label="label")
tf_serving_dataset = tfdf.keras.pd_dataframe_to_tf_dataset(pd_serving_dataset)

In [ ]:
model = tfdf.keras.RandomForestModel(verbose=0)
model.fit(tf_train_dataset)

In [ ]:
model.predict(tf_serving_dataset,verbose=0)[:10]

array([[0.9899992 ],
       [0.        ],
       [0.99999917],
       [0.06000001],
       [0.99999917],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.99999917],
       [0.        ]], dtype=float32)