<a href="https://colab.research.google.com/github/jaydeep-aspire/practice/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!pip install tensorflow_decision_forests


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 49.2 MB/s eta 0:00:00


In [8]:
import tensorflow_decision_forests as tfdf
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import math

In [9]:
pd_dataset = pd.DataFrame({
    "feature_1": [1,2,3],
    "feature_2": ["a", "b", "c"],
    "label": [0, 1, 0],
})
pd_dataset

feature_1 feature_2  label
0          1         a      0
1          2         b      1
2          3         c      0

In [10]:
tf_dataset = tfdf.keras.pd_dataframe_to_tf_dataset(pd_dataset,label="label")
for features,label in tf_dataset:
  print(features)
  print(label)

{'feature_1': <tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>, 'feature_2': <tf.Tensor: shape=(3,), dtype=string, numpy=array([b'a', b'b', b'c'], dtype=object)>}
tf.Tensor([0 1 0], shape=(3,), dtype=int64)


In [11]:
pd_train_dataset = pd.DataFrame({
    "feature_1": np.random.rand(1000),
    "feature_2": np.random.rand(1000),
})
pd_train_dataset["label"] = pd_train_dataset["feature_1"] > pd_train_dataset["feature_2"]

pd_train_dataset

feature_1  feature_2  label
0     0.487376   0.205888   True
1     0.831134   0.637312   True
2     0.478197   0.365974   True
3     0.080673   0.217752  False
4     0.335291   0.480516  False
..         ...        ...    ...
995   0.614464   0.446536   True
996   0.233755   0.533965  False
997   0.476834   0.343806   True
998   0.190840   0.672626  False
999   0.439424   0.026982   True

[1000 rows x 3 columns]

In [12]:
pd_serving_dataset = pd.DataFrame({
    "feature_1": np.random.rand(500),
    "feature_2": np.random.rand(500),
})

pd_serving_dataset

feature_1  feature_2
0     0.454532   0.748641
1     0.973768   0.832617
2     0.204209   0.865197
3     0.841159   0.588707
4     0.965525   0.732980
..         ...        ...
495   0.785747   0.511143
496   0.145022   0.763840
497   0.042453   0.925052
498   0.983029   0.493484
499   0.119172   0.527625

[500 rows x 2 columns]

In [13]:
tf_train_dataset = tfdf.keras.pd_dataframe_to_tf_dataset(pd_train_dataset, label="label")
tf_serving_dataset = tfdf.keras.pd_dataframe_to_tf_dataset(pd_serving_dataset)

In [14]:
model = tfdf.keras.RandomForestModel(verbose=0)
model.fit(tf_train_dataset)

In [15]:
model.predict(tf_serving_dataset,verbose=0)[:10]

array([[0.        ],
       [0.9899992 ],
       [0.        ],
       [0.99999917],
       [0.99999917],
       [0.        ],
       [0.99999917],
       [0.99999917],
       [0.99999917],
       [0.        ]], dtype=float32)